"""ingredient molecular descriptors and formula library

Revision ID: 1aadfed13cf6
Revises: 5158e2378926
Create Date: 2026-09-18 07:52:23.436395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1aadfed13cf6'
down_revision: Union[str, Sequence[str], None] = '5158e2378926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('formula_library',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=128), nullable=True),
    sa.Column('domain', sa.String(length=64), nullable=True),
    sa.Column('product_family', sa.String(length=128), nullable=True),
    sa.Column('origin_type', sa.String(length=64), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('training_eligible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formula_library_ingredients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formula_library_id', sa.String(length=64), nullable=False),
    sa.Column('phase', sa.String(length=1), nullable=False),
    sa.Column('inci', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('weight_pct', sa.Float(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['formula_library_id'], ['formula_library.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_formula_library_ingredients_formula_library_id'), 'formula_library_ingredients', ['formula_library_id'], unique=False)
    op.add_column('ingredients', sa.Column('entity_type', sa.String(length=32), nullable=True))
    op.add_column('ingredients', sa.Column('identity_source', sa.String(length=64), nullable=True))
    op.add_column('ingredients', sa.Column('identity_confidence', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('structure_representation_type', sa.String(length=64), nullable=True))
    op.add_column('ingredients', sa.Column('molecular_weight', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('logp', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('tpsa', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('hbd', sa.Integer(), nullable=True))
    op.add_column('ingredients', sa.Column('hba', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'hba')
    op.drop_column('ingredients', 'hbd')
    op.drop_column('ingredients', 'tpsa')
    op.drop_column('ingredients', 'logp')
    op.drop_column('ingredients', 'molecular_weight')
    op.drop_column('ingredients', 'structure_representation_type')
    op.drop_column('ingredients', 'identity_confidence')
    op.drop_column('ingredients', 'identity_source')
    op.drop_column('ingredients', 'entity_type')
    op.drop_index(op.f('ix_formula_library_ingredients_formula_library_id'), table_name='formula_library_ingredients')
    op.drop_table('formula_library_ingredients')
    op.drop_table('formula_library')
    # ### end Alembic commands ###
