"""consolidate formula history into formulas table

Revision ID: 28cd1c7a5108
Revises: 1aadfed13cf6
Create Date: 2026-09-18 08:09:27.961199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '28cd1c7a5108'
down_revision: Union[str, Sequence[str], None] = '1aadfed13cf6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_formula_library_ingredients_formula_library_id'), table_name='formula_library_ingredients')
    op.drop_table('formula_library_ingredients')
    op.drop_table('formula_library')
    op.add_column('formula_ingredients', sa.Column('role', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formula_ingredients', 'role')
    op.create_table('formula_library',
    sa.Column('id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('domain', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('product_family', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.Column('origin_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('source_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('training_eligible', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('formula_library_pkey'))
    )
    op.create_table('formula_library_ingredients',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('formula_library_id', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('phase', sa.VARCHAR(length=1), autoincrement=False, nullable=False),
    sa.Column('inci', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('weight_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['formula_library_id'], ['formula_library.id'], name=op.f('formula_library_ingredients_formula_library_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('formula_library_ingredients_pkey'))
    )
    op.create_index(op.f('ix_formula_library_ingredients_formula_library_id'), 'formula_library_ingredients', ['formula_library_id'], unique=False)
    # ### end Alembic commands ###
