"""ingredient descriptors and formula ingredient role

Revision ID: 7188dc43a521
Revises: 8cb93f4ce1f1
Create Date: 2026-09-18 08:56:19.242748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7188dc43a521'
down_revision: Union[str, Sequence[str], None] = '8cb93f4ce1f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formula_ingredients', sa.Column('role', sa.String(length=64), nullable=True))
    op.add_column('ingredients', sa.Column('entity_type', sa.String(length=32), nullable=True))
    op.add_column('ingredients', sa.Column('identity_source', sa.String(length=64), nullable=True))
    op.add_column('ingredients', sa.Column('identity_confidence', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('molecular_weight', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('logp', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('tpsa', sa.Float(), nullable=True))
    op.add_column('ingredients', sa.Column('hbd', sa.Integer(), nullable=True))
    op.add_column('ingredients', sa.Column('hba', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'hba')
    op.drop_column('ingredients', 'hbd')
    op.drop_column('ingredients', 'tpsa')
    op.drop_column('ingredients', 'logp')
    op.drop_column('ingredients', 'molecular_weight')
    op.drop_column('ingredients', 'identity_confidence')
    op.drop_column('ingredients', 'identity_source')
    op.drop_column('ingredients', 'entity_type')
    op.drop_column('formula_ingredients', 'role')
    # ### end Alembic commands ###
